<p>refer to: <br /><a href="https://github.com/vulmon/Vulmap/tree/master/Vulmap-Linux " target="_blank">https://github.com/vulmon/Vulmap/tree/master/Vulmap-Linux</a>
</p>
<h3>安装</h3>
<p>git clone <a href="https://github.com/vulmon/Vulmap.git " target="_blank">https://github.com/vulmon/Vulmap.git</a>
</p>
<h3>使用</h3>
<p>cd Vulmap-Linux</p>
<p>pip3 vulmap-linux.py -h</p>
<p><img src="https://files.sweetysoft.com/blog_images/from_paste_20230502_083934.png" /></p>
<p>现在遇到的问题是无法使用。</p>
<p>需要先 python3 vulmap-linux.py -a 来下载所有的exploit 或者cve, 目前看起来是没有的。</p>
<p>issue: <br /><a href="https://github.com/vulmon/Vulmap/issues/30 " target="_blank">https://github.com/vulmon/Vulmap/issues/30</a>
</p>
<h3>结论</h3>
<p>目前无法使用</p>
